
a = 115         #int -> string
b = 3.14        #float -> string
c = "68"        #string -> int
d = "True"      #string -> boolean
e = True        #boolean -> string
f = False       #boolean -> string
g = '10110111'  #byte -> int
h = "2.54"      #string -> float
i = 100         #int -> float
j = 10.0        #float -> int
k = 254         #int -> byte

a_str = str(a)
print(a_str)
b_float = str(b)
print(b_float)
c_str = int(c)
print(c_str)
d_str = bool(d)
print(d_str)
e_val = str(e)
print(e_val)
f_val = str(f)
print(f_val)
g_byte = int(g)
print(g_byte)
j_float = float(j)
print(j_float)
byte_k = bin(k)
print(byte_k)
