user_input1 = input("what is your favrite animal ")
print("You entered: " + user_input1)
user_input2 = input("why is it your favrite animal ")
print("You entered: " + user_input2)
user_input3 = input("where do they live ")
print("You entered: " + user_input3)
user_input4 = input("what is a fun fact about them ")
print("You entered: " + user_input4)
print("So your favorite animal is " + user_input1 + "? and you like theme because? " + user_input2 + " where do they live " + user_input3 + " what is a fun fact about them " + user_input4)